# This rule is not used by the project tip itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to apps.tip.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tip
    app.kubernetes.io/managed-by: kustomize
  name: application-viewer-role
rules:
- apiGroups:
  - apps.tip.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.tip.io
  resources:
  - applications/status
  verbs:
  - get
